### ISSUE TITLE
operator does not exist: uuid ~~ unknown QueryFailedError: operator does not exist: uuid ~~ unknown

### ISSUE THREAD

**Issue by helsonxiao** [SoftwareBrothers/adminjs-typeorm#32]
Hi, I cannot filter record by uuid in typeorm. I've seen a same issue in `adminjs-sequelizejs`.

SQL logs:
```
query: SELECT ... FROM "assessment_session" "AssessmentSession" WHERE "AssessmentSession"."uuid" LIKE $1 ORDER BY "AssessmentSession"."id" ASC LIMIT 10 -- PARAMETERS: ["%ad95965f-0ef2-4496-b583-e43b5de50011%"]
query failed: SELECT ... FROM "assessment_session" "AssessmentSession" WHERE "AssessmentSession"."uuid" LIKE $1 ORDER BY "AssessmentSession"."id" ASC LIMIT 10 -- PARAMETERS: ["%ad95965f-0ef2-4496-b583-e43b5de50011%"]
error: error: operator does not exist: uuid ~~ unknown
    at Parser.parseErrorMessage (/Users/helsonxiao/qingzhou-be/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/helsonxiao/qingzhou-be/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/helsonxiao/qingzhou-be/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/helsonxiao/qingzhou-be/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 202,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No operator matches the given name and argument types. You might need to add explicit type casts.',
  position: '1026',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_oper.c',
  line: '731',
  routine: 'op_error'
}
```

properties:
```
properties: {
  uuid: {
    isVisible: {
      show: true,
      filter: true,
    },
    isTitle: true,
  },
}
```

**Comment by helsonxiao** [comment]
https://github.com/SoftwareBrothers/adminjs/issues/932

**Comment by slidenerd** [comment]
There is still an issue here. 
The postgres UUID column allows you to store this value '8b141381-7a98-d85e-7cae-79f9233e0aef'
This is not a valid UUID but rather an MD5 hash that I am generating from a combination of columns in my row and then storing it
Adminjs gives you an error when you try searching by this value

```

original: error: operator does not exist: uuid ~~ unknown
      at Parser.parseErrorMessage (/Users/vr/Desktop/code/vr/api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/vr/Desktop/code/vr/api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/vr/Desktop/code/vr/api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/vr/Desktop/code/vr/api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 201,
    severity: 'ERROR',
    code: '42883',
    detail: undefined,
    hint: 'No operator matches the given name and argument types. You might need to add explicit type casts.',
    position: '167',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_oper.c',
    line: '656',
    routine: 'op_error',
    sql: `SELECT "id", "author", "content", "guid", "link", "pubdate", "summary", "tags", "title", "feed_id" AS "feedId" FROM "feed_items" AS "FeedItem" WHERE ("FeedItem"."id" LIKE '%8b141381-7a98-d85e-7cae-79f9233e0aef%') ORDER BY "FeedItem"."id" ASC LIMIT 10 OFFSET 0;`,
    parameters: undefined
  },
  sql: `SELECT "id", "author", "content", "guid", "link", "pubdate", "summary", "tags", "title", "feed_id" AS "feedId" FROM "feed_items" AS "FeedItem" WHERE ("FeedItem"."id" LIKE '%8b141381-7a98-d85e-7cae-79f9233e0aef%') ORDER BY "FeedItem"."id" ASC LIMIT 10 OFFSET 0;`,
  parameters: {}
}
```

The reason this is happening is because of [THIS LINE](https://github.com/SoftwareBrothers/adminjs-sequelizejs/blob/master/src/utils/convert-filter.ts#L18)

It fails the isUUID check and goes into the else condition and tries to apply an ILIKE operator to what is still considered a UUID. How to resolve this?
