### ISSUE TITLE
How to solve "Trying to bundle file but it doesn't exist"

### ISSUE THREAD

**Issue by Paroca72** [SoftwareBrothers/adminjs-typeorm#62]
Hello,

Need help to sort out this issue.
I'm trying to create some custom components in AdminJS and I take the code from: [ui-customization](https://docs.adminjs.co/ui-customization/writing-your-own-components?_gl=1*n1q5f3*_gcl_au*MTcyNzExOTIxLjE2ODc0ODg5NzY.)
The only difference I'm not using TS but just JS.

**my-input.jsx**
```
import React from 'react'

// just some regular React component
const MyInputComponent = () => <input />

export default MyInputComponent
```

**component.js**
```
import { ComponentLoader } from 'adminjs'

const componentLoader = new ComponentLoader()

const Components = {
    MyInput: componentLoader.add('MyInput', './my-input'),
}

export { componentLoader, Components }
```

But what I got is always:
```
(node:4628) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
file:///C:/Users/.../Desktop/Projects/.../.../Website/node_modules/adminjs/lib/backend/utils/component-loader.js:80
    throw new ConfigurationError(`Trying to bundle file '${src}' but it doesn't exist`, 'AdminJS.html');
          ^

ConfigurationError:
    Trying to bundle file '\C:\Users\Samuele\Desktop\Projects\...\...\Website\app\components\my-input' but it doesn't exist
    More information can be found at: https://docs.adminjs.co/AdminJS.html

    at ComponentLoader.resolveFilePath (file:///C:/Users/.../Desktop/Projects/.../.../Website/node_modules/adminjs/lib/backend/utils/component-loader.js:80:11)
    at ComponentLoader.add (file:///C:/Users/.../Desktop/Projects/.../.../Website/node_modules/adminjs/lib/backend/utils/component-loader.js:8:46)
    at file:///C:/Users/.../Desktop/Projects/.../.../Website/app/components/components.js:6:30
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

Node.js v18.16.0
**NOTE:** The path are checked and correct.. now use"..." just for privacy.

I read need to use babel-node and I did but it seems I wrong something in the configuration.

**.babelrc**
```
{
    "presets": [
        [
            "@babel/env",
            {
                "targets": {
                    "node": "current"
                }
            }
        ]
    ],
    "plugins": [
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-proposal-object-rest-spread"
    ]
}
```

**package.json**
```
{
  "scripts": {
    "build": "babel index.js -d dist",
    "start": "npm run build && nodemon dist/index.js"
  },
  "type": "module",
  "dependencies": {
    "@adminjs/express": "^6.0.0",
    "@adminjs/sequelize": "^4.0.0",
    "adminjs": "^7.0.7",
    "babel-node": "^0.0.1-security",
    "connect-session-sequelize": "^7.1.7",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "mssql": "^9.1.1",
    "openai": "^3.3.0",
    "sequelize": "^6.32.1",
    "tedious": "^16.1.0",
    "tslib": "^2.6.0"
  },
  "devDependencies": {}
}

```

Very thanks
Sam

**Comment by Paroca72** [comment]
Sorry wrong place
